name: CI

on: [ push, pull_request ]

jobs:

    build:

        name: "Check"

        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]

        runs-on: ${{ matrix.os }}

        steps:

            -   name: "git clone"
                uses: actions/checkout@v4

            -   name: "setup jdk"
                uses: actions/setup-java@v3
                with:
                    java-version: 8
                    distribution: temurin

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: "./gradlew build"
                run: ./gradlew --scan --no-daemon build
                env:
                    CI: true

            -   name: "git diff --exit-code"
                run: git diff --exit-code
